language: ruby
rvm:
- 2.5.0
bundler_args: --jobs=2
before_script:
  - bundle install
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rspec
before_install:
  -gem install -v 1.17.3 bundler --no-rdoc --no-ri
services:
  - postgresql
